### ISSUE TITLE
[feat] Create Individual Project Page on Admin Dashboard

### ISSUE THREAD

**Issue by itsliterallymonique** [calblueprint/ace-ny#18]
This sprint, you will be making the project page and displaying the project information from the database on Retool (so fun :0)! Here is what you must do:

1. [chore] Change the “All Projects” Table to also include the project image – there is a field type called image
2. Add the “All Projects” section to a container and enable multiple views
3. Add a form to the second view and rename the views to be descriptive!
           1. Click on generate from table and display these properties on the form:
            - Project Image
            - Project Name
            - Developer
            - Renewable Energy Category – as “multiselect”
            - Size (watts)
            - Project Status – as “select”
            - Zip Code
            - Longitude
            - Latitude
            - County
            - Town
            - Region
            - State Senate District
            - Assembly District
            - Proposed COD
            - Additional Information
           2. Fix the layout and styling so that it looks clean and organized
4. Connect the “Submit” button on the form so that it will update the Project entry on the database
5. Test it out -- Make a tester entry in Supabase and check your form works :) !
6. Add Documentation to our MTP Documentation notion page! [https://www.notion.so/calblueprint/MTP-Documentation-4e9963e4e70d42209a1f26963b3da10b](https://www.notion.so/calblueprint/MTP-Documentation-4e9963e4e70d42209a1f26963b3da10b) [make sure it goes over how to fill out the form + submit!]
7. If you're done, here are some optional sprints:
           a. [change divs to styled components in modal](https://github.com/calblueprint/ace-ny/issues/21)
           b. [your next week's sprint](https://github.com/calblueprint/ace-ny/issues/20)

Here’s a short video tutorial I found if you need help! [https://www.youtube.com/watch?app=desktop&v=v1YfE9gSaoM](https://www.youtube.com/watch?app=desktop&v=v1YfE9gSaoM)

PR Reviewer: @itsliterallymonique and @nehaahussain

**Comment by jjstnlee** [comment]
I am done :3

**Comment by itsliterallymonique** [comment]
Looks good Justin!
