### ISSUE TITLE
[fix] small changes to NYSERDA & NYISO scraper

### ISSUE THREAD

**Issue by itsliterallymonique** [calblueprint/ace-ny#24]
This sprint, you will need to make a few small changes to your NYSERDA scraper based on feedback we were given by the NPO.
First here are some notes, just for your information (you’re doing so good Deena):
- **Small solar project:** many don’t have names, so **project ID is sufficient!**
- Normally we should **default to data provided by NYSERDA** (if there are duplicate fields in the NYISO)
- Your method for getting latitude and longitude for small solar projects **was accepted**. But we will need some sort of disclaimer that the locations may not be 100% accurate somewhere on the website _(this is a design problem so don’t worry about this)_

Here is what you must do:

1. Project Size Fields
          a. **Small Solar Projects:** Project Size field will be **PV System Size** (of Estimated PV System Size if PV System Size is empty) AND only get projects **larger than 2 MW (2000kW)**
          b. **Large-scale project** dataset: use **New Renewable Capacity** (MW)
          c. Make sure you convert them both to MW!!
2. Proposed COD:
          a. Use NYISO Proposed COD category for this. If there is none, leave it as NULL
3. Renewable Energy Technology
          a. Only collect data with the following Energy Technology Categories: Hydroelectric, Land Based Wind, Offshore Wind, Solar, Geothermal, Energy Storage (ES), Pumped Storage (PS)
4. New field to scrape: Permit Process
          a. It’ll tell us if the project is undergoing their permit process w/ ORES or another one – this field will likely help us when we scrape from the ORES
          b. Also add the Permit Process to the supabase and schema (**types** >> **schema.d.ts**)?

**You are doing so amazing Deena**! Thank you so much for all your hard work <3 I appreciate you so much!!!

**Comment by deenasun** [comment]
@itsliterallymonique the small solar database only has like 3 projects that have a size greater than 2,000 kw out of the 230,000 projects they have. Am I understanding correctly that we should only keep those 3?
