### ISSUE TITLE
[feat] Continue Connecting NYISO and NYSERDA, and add Key Development Milestones

### ISSUE THREAD

**Issue by itsliterallymonique** [calblueprint/ace-ny#32]
This week, you will continue your previous sprint and also work on some fixes based on the NPO's responses to our questions! Here is what you will do:

1. Make the fixes described in this issue: https://github.com/calblueprint/ace-ny/issues/24
2. Don’t override any fields with NYISO – only use NYISO if the fields are empty from NYSERDA
3. Add projects from NYISO that are not in NYSERDA
4. Collect additional data for KDMs as a json
       a. Format will be = Key: [KDM NAME], Completed: ‘T/F’, Date: ‘date/null’
       b. NYISO: Entry to NYISO queue, Execution of an Interconnection Agreement (IA), Start of operations
       c. NYSERDA: Winning a contract award from NYSERDA
       d. [DON’T WORRY ABT - ORES: Application for permit to ORES, Issuance of permit from ORES]
9. Renewable energy technology:
       a. Only collect data whose renewable energy technology is in the list
       b. TODO: map the abbreviated energy technologies from the NYISO data to readable string
       c. Standardize the tech names that are pushed into the database
13. NYISO is missing built-in data on region, zipcode, and latitude/longitude. For NYISO data that doesn't directly match any existing Supabase data and that we plan to insert directly, how should we estimate and obtain information for those fields?
       a. Interconnection points to reverse geocode data from NYISO

**Comment by itsliterallymonique** [comment]
@deenasun 
KDM json should look something like:
<img width="550" alt="Screenshot 2024-10-25 at 3 14 44 PM" src="https://github.com/user-attachments/assets/395c292c-a64e-4994-9374-ccc0ca421843">

**Comment by deenasun** [comment]
TODO:
- KDMs
- reverse geocode NYISO locations
