### ISSUE TITLE
[feat] Check for Project Details that have been Updated

### ISSUE THREAD

**Issue by itsliterallymonique** [calblueprint/ace-ny#68]
This sprint, you will work on checking if there have been any updates or changes to existing projects! Here is what you need to do for each dataset

1. Make these small changes
        a. Solar is now **Solar PV**
        b. We will need to fix how we check for the “NYSERDA contracted” KDM
        c. If the project is in the NYSERDA, it has been contracted!
        d. To get the date, check solicitation_name – if it is in the form of RESRFP20-1, we can collect the year (in this case it’s 2020) → RESRFPXX-1 means the year is 20XX
        e. IA Executed is instead IA Tendered
2. NYSERDA
        a. Use the data_through_date to check if it was updated since the last webscraper run
        b. Compare data such as solicitation name (for KDM), project status (has it become “canceled” if so, remove it from the database), New Renewable Capacity (size), Permit Process, etc. and see if anything has been changed
3. NYISO
        a. Check if any projects have been canceled (have the been moved to the “Withdrawn” tab in the spreadsheet?). If they have, remove them from the database
        b. Check the “Last Updated Date” column to see if it was updated since the last webscraper run
        c. Check if any projects have been moved from Interconnection Queue → In Service (set the status from proposed to operational and change operations begun to TRUE)
        d. We’re going to check for updates for these fields: IA tender date, Proposed COD, Date of IR, (let me know if there’s anything we’re missing!)
4. ORES
        a. Check if the project is now in Permitted Applications or Complete Applications Under Review and adjust the KDMs accordingly
        b. (Permitted Applications is the last step for ORES, so if the project already has Permitted Application as TRUE for the KDM, we don’t need to check for it)

**Comment by deenasun** [comment]
`c. Check if any projects have been moved from Interconnection Queue → In Service (set the status from proposed to operational and change operations begun to TRUE)` --> this should already be handled by the way that the webscraper for NYISO works because the function sets the status for any "In Service" projects to "Operational" already and any newer projects with a more recent "last_updated" field that matches existing data in the database will override the project status if it's different
