### ISSUE TITLE
[feat] Hiding Markers when Search and Filters are Activated

### ISSUE THREAD

**Issue by itsliterallymonique** [calblueprint/ace-ny#80]
This week, you will be working on the Google Maps API. What we want to do is hide any markers that are not part of the search / filter results. Google Maps is a little difficult, so please reach out to me (Monique) if you are stuck and we can figure it out together. Here is what you will need to do:

1. Go to api >> maps >> AddMarkers. Make sure you understand what the functions do (have any questions? DM the Slack chat with me (Monique) + Ethan)
2. We are going to want to pass in a prop to this component that holds the filtered projects (e.g. filteredProjects)!
3. Create 2 functions, one will hide specific marker, the other will make it appear on the map (remember, we don’t want to delete a marker because that makes it difficult to add it back.
           a. Look at the setMap() function – setMap(null) will hide the markers and if you pass in “`map`”, it will reappear
           b. Documentation: [https://developers.google.com/maps/documentation/javascript/examples/marker-remove](https://developers.google.com/maps/documentation/javascript/examples/marker-remove)
4. Create a useEffect that will run when there are changes to the filteredProjects
           a. It will iterate through all the project markers to 1) hide projects not in filteredProjects and 2) make sure to show projects that are in filteredProjects
           b. I believe markers have project_id attached to it as the key!
           c. To test your function works, try to use the direct search and see if it will filter the markers
5. You can also add other properties to the marker such as status and projectSize (this is optional)

**Comment by ethan-tam33** [comment]
@itsliterallymonique I think my PR [here](https://github.com/calblueprint/ace-ny/pull/85) addresses this sprint since the markers not part of the filtered group do not appear.
