### ISSUE TITLE
[feat] Create the Admin Dashboard Home Page

### ISSUE THREAD

**Issue by itsliterallymonique** [calblueprint/ace-ny#9]
This week you will be working on retool! [every developer will have a retool sprint at least once this semester]. You will be setting up the retool page based on Josh’s lowfis

You don't need to submit a PR, instead write documentation on what you did in our MTP Documentation file in our notion. Then tag Monique and your PR reviewer.

What you will need to do:

- Create a page on retool called “All Projects”
- Inside the “All Projects” retool page add the following features
         - A search bar
         - A table that displays all the projects. 
         - The table should display the following features: 
            .        - Project Name, 
            .        - Developer, 
            .        - Renewable Energy Category, 
            .        - Size (Watts), 
            .        - Project Status, 
            .        - County, 
            .        - Town, 
            .        - Region, 
            .        - State Senate District, 
            .        - Assembly District, 
            .        - Zip Code,
            .        - Additional Information

To do this, here are some steps you will need to follow:
1. Go to retool and open the ACE NY admin dashboard app (select “edit” to make changes to it)
2. The database has already been uploaded under “Supabase Database”, so whenever you make any queries use this!
3. Drag and drop a table component into the “allProjects” page.
         a. Connect our Supabase Database
         b. Make a query to collect all the data from the projects table (you can query using SQL)
         c. Here are some resources to help you make the query + table
            .        i. [https://www.youtube.com/watch?v=AgB2-CSrnoI](https://www.youtube.com/watch?v=AgB2-CSrnoI)
            .        ii. [https://www.youtube.com/watch?v=sv5niaHKo5g](https://www.youtube.com/watch?v=sv5niaHKo5g)
4. Add a title / label for the table containing "All Projects"
         a. Use the text component
5. To make the search bar, drag and drop the text input component
         a. You want the user to be able to search by the project name
         b. Here are a few resources for help in doing this:
            .        i. [https://www.youtube.com/watch?v=5u8Put5fugk](https://www.youtube.com/watch?v=5u8Put5fugk)
            .        ii.[ https://www.youtube.com/watch?v=G7FwV9H6Mnk]( https://www.youtube.com/watch?v=G7FwV9H6Mnk)

For reference, the page should look something like this [DON'T ADD THE VIEW PROJECTS / ADD PROJECT TAB YET]
![IMG_6136](https://github.com/user-attachments/assets/a35a7ef9-473f-48c5-8c3a-22282cfd194a)

PR Reviewers: Ethan Tam (@ethan-tam33) and Monique (@itsliterallymonique)

**Comment by itsliterallymonique** [comment]
@nehaahussain 
Awesome job Neha! Can you make it so that the user can only search by project name? Other than that looks good!

**Comment by nehaahussain** [comment]
> @nehaahussain Awesome job Neha! Can you make it so that the user can only search by project name? Other than that looks good!

@itsliterallymonique Just updated it!

**Comment by itsliterallymonique** [comment]
> > @nehaahussain Awesome job Neha! Can you make it so that the user can only search by project name? Other than that looks good!
> 
> @itsliterallymonique Just updated it!

@nehaahussain amazing thank you! Once Ethan checks the PR + approves it, you can close the issue!

**Comment by ethan-tam33** [comment]
Looks good to me!
