### ISSUE TITLE
[documentation] Finish documentation for the Home Page, Marker Functionality, Technology Filter, and Admin Dashboard

### ISSUE THREAD

**Issue by itsliterallymonique** [calblueprint/ace-ny#99]
Write all your documentation for Home Page and Marker functionalities in our [MTP documentation page](https://www.notion.so/calblueprint/MTP-Documentation-4e9963e4e70d42209a1f26963b3da10b). **_Please FULLY read this sprint description and closely follow these instructions, as it is important you adhere strictly to what I instruct you to do._** If you have any issues or questions feel free to DM me about them.
**Firstly, your documentation should consist of:**

1. Descriptions and sentences. They should be informative and concise, and inform the user on HOW to access, user or understand the feature. Other than the web scraper, this documentation does not need to describe specific code.
2. At least 1 image per subheader that shows and displays the feature
3. If an action will be taken, create a video or GIF to show how to take the specific action.

**Here is what documentation you must write:**

1. Navigating the map. Under this subheader, describe:
      a. How to zoom in & out of the map
      b. How to pan around the map
      c. Any other important navigational features
2. Project Markers. Under this subheader, describe:
      a. what the project markers represent and what they look like
      b. what the different custom marker icons mean
3. Accessing Project Name via Info Window. Under this subheader, describe:
      a. the process the user has to take in order to access the project name
4. Marker Clustering. Under this subheader, describe:
      a. What marker clustering is, and what a marker cluster looks like
      b. How to zoom in and access the projects inside the cluster
5. Open the individual project modal. Under this subheader, describe:
      a. Describe how to access the project modal using the project marker
      b. Explain what happens once you select the project marker
      c. Any other features in marker selection
6. Filtering by technology. Under this subheader, describe:
      a. Describe how to select technologies and emphasize it is a multiselect
      b. Explain how to actually apply the filter
      c. Describe what happens once you filter
      d. Detail how to exit out of the filter
      e. Describe how to clear the filter
7. Approving Projects. Under this subheader, describe:
      a. What does approving a project mean?
      b. How to access the approving project page
      c. The process of how to approve a project
      d. What happens once we approve the project
8. Deleting a Project. Under this subheader describe:
      a. What does it mean to delete a project?
      b. How to delete a project.

**Comment by ethan-tam33** [comment]
Finished documentation [here](https://www.notion.so/calblueprint/MTP-Documentation-4e9963e4e70d42209a1f26963b3da10b)!

**Comment by itsliterallymonique** [comment]
thanks ethan!
